import "server-only";

// Minimal bundled breached/common-password list (security.md AUTH-2).
// In production this would be a larger curated list (e.g. SecLists top-10k).
// Comparison is case-insensitive and trimmed.
const COMMON_BREACHED = new Set<string>(
  [
    "password",
    "password1",
    "password123",
    "passw0rd",
    "p@ssw0rd",
    "p@ssword1",
    "qwerty",
    "qwerty123",
    "qwertyuiop",
    "123456",
    "12345678",
    "123456789",
    "1234567890",
    "11111111",
    "00000000",
    "abc123",
    "abcdef",
    "abcdefgh",
    "letmein",
    "letmein123",
    "iloveyou",
    "iloveyou1",
    "welcome",
    "welcome1",
    "welcome123",
    "admin",
    "admin1",
    "administrator",
    "monkey",
    "monkey123",
    "dragon",
    "dragon123",
    "football",
    "baseball",
    "basketball",
    "sunshine",
    "princess",
    "superman",
    "trustno1",
    "ninja",
    "master",
    "shadow",
    "freedom",
    "starwars",
    "computer",
    "secret",
    "secret123",
    "changeme",
    "changeme1",
    "changeme123",
    "tennis",
    "tennis123",
    "matchpoint",
    "doublefault",
    "deuceace",
    "qwerty12345",
    "1q2w3e4r",
    "1q2w3e4r5t",
    "asdfghjkl",
    "zxcvbnm",
    "passwordpassword",
    "letmein2024",
    "letmein2025",
    "letmein2026",
    "summer2024",
    "summer2025",
    "winter2024",
    "winter2025",
    "spring2025",
    "autumn2025",
    "funcap",
    "funcap123",
    "funcappassword",
  ].map((p) => p.toLowerCase()),
);

export function isBreachedPassword(password: string): boolean {
  return COMMON_BREACHED.has(password.trim().toLowerCase());
}
